### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by renatolond** [tamarasaurus/throwbacks#1]
Hello!
I'm trying to run it using Gulp 3.9.1, Node v6.3.1, but after doing an npm install, if I just try to run gulp, I still get:
```
$ gulp
(node:5726) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/home/renatocerqueira/src/throwbacks/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/renatocerqueira/src/throwbacks/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/renatocerqueira/src/throwbacks/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/renatocerqueira/src/throwbacks/node_modules/gulp-sass/index.js:3:17)
```

And if I just try to run it directly with `node index.js` I get:
```
 $ node index.js
module.js:442
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/renatocerqueira/src/throwbacks/libs/throwback.js:3:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Even the trying the test target seems to have some errors:
```
$ npm test

> throwbacks@0.0.0 test /home/renatocerqueira/src/throwbacks
> test

npm ERR! Test failed.  See above for more details.
```

Should I try with an older node version?

**Comment by tamarasaurus** [comment]
Hi Renato,

To address your first issue - try running `npm rebuild node-sass`. If that doesn't fix things, I would follow the instructions in the node-sass troubleshooting guide - https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md

The entrypoint to the app frontend should be through gulp (and run node index to get the backend running).  To get `node index` running, create a file in the `libs` folder called `config.js` with the following contents:

```javascript
module.exports = {
    appKey: '__YOUR__APP__KEY',
    appSecret: '__YOUR__APP__SECRET'
}
```

To get the key and secret values, you need to set up an app on the Spotify website https://developer.spotify.com/my-applications/#!/

**Comment by renatolond** [comment]
Hi Tamara,
Thanks for the quick response :)
Creating the config.js indeed fixed the config issue.

For the env issues, I tried starting the app on a fresh docker environment, doing this:
`docker run -it --rm --name my-running-script -v "$PWD":/usr/src/app --expose 8888 -P -w /usr/src/app node:4 /bin/bash -l`
And inside the container:
`# npm install -g gulp; npm install node-sass; npm install; gulp`

Which after a lot of installing, get to this part:
```
(...)
npm WARN unmet dependency /usr/src/app/node_modules/gulp-sass requires node-sass@'^2.0.1' but will load
npm WARN unmet dependency /usr/src/app/node_modules/node-sass,
npm WARN unmet dependency which is version 3.8.0
npm info ok
[13:34:02] Using gulpfile /usr/src/app/gulpfile.js
[13:34:02] Starting 'watch'...
[13:34:02] Finished 'watch' after 9.51 ms
[13:34:02] Starting 'sass'...
[13:34:02] Finished 'sass' after 8.79 ms
[13:34:02] Starting 'js'...
[13:34:02] Finished 'js' after 19 ms
[13:34:02] Starting 'default'...
[13:34:02] Finished 'default' after 6.61 μs
Compiled
```
If I try to connect to the port 8888, I don't get anything.
And if I try to do `node index`, I get this:

```
# node index
module.js:327
    throw err;
    ^

Error: Cannot find module 'swig'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/index.js:13:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

If I try to install the sass version it suggests `node-sass@'^2.0.1'`, I get this error instead:

```
> node-sass@2.1.1 postinstall /usr/src/app/node_modules/node-sass
> node scripts/build.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/usr/src/app/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
Build failed
```

Sorry if I'm asking obvious questions here!
Best,

**Comment by tamarasaurus** [comment]
For the swig error, running `npm install --save-dev swig` should fix it

The versions of gulp and node-sass in this project are a year old, it might be worth updating these dependencies in your fork (I haven't touched this project in a while). For the node-gyp error, you would need to follow the instructions specific to your environment outlined here - https://www.npmjs.com/package/node-gyp

**Comment by renatolond** [comment]
Hi Tamara!
With the swig install it seems I can run the app.
I haven't forked it yet, but if I do I'll look into updating the versions.
Thanks for the replies!
